[package]
name = "common-structs"
version = "0.0.0"
authors = ["catalin-neagu <catalin.neagu@dharitri.com>"]
edition = "2018"

[lib]
path = "src/model.rs"
[dependencies.dharitri-sc]
version = "0.12.0"
