[package]
name = "safety-module-meta"
version = "0.0.0"
authors = ["CostinCarabas <costin.carabas@dharitri.com>"]
edition = "2018"
publish = false
[dependencies.safety-module]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.12.0"
